language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

stages:
  - name: test
    if: type = pull_request AND branch = master
  - name: deploy
    if: type = push AND branch = master

jobs:
  include:
    - stage: test
      script: 
        - npx eslint ./src ./server
        - npm run build
    - stage: deploy
      script: 
        - npm run build
        - zip -q -r latest .
        - mkdir -p dpl_cd_upload
        - mv latest.zip dpl_cd_upload/latest.zip
      deploy:
      - provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        local_dir: dpl_cd_upload
        skip_cleanup: true
        on: &2
          repo: rudotriton/smart-budgets
        bucket: smartbudgets
        region: eu-west-1
      - provider: codedeploy
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: smartbudgets
        key: latest.zip
        bundle_type: zip
        application: smartbudgets
        deployment_group: primary
        region: eu-west-1
        on: *2
              